# Generated by Django 5.1.1 on 2024-09-17 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_application_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='ItemEntry',
        ),
    ]
