# Generated by Django 5.1.1 on 2024-09-21 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_itementry_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itementry',
            name='user',
        ),
    ]
