# Generated by Django 5.1.1 on 2024-10-09 03:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_itementry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itementry',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
